#pragma once

// =====
// enums
// =====
enum SHADER_RESOURCE_TYPE : UINT8 {
	SHADER_RESOURCE_TYPE_CONSTANT_BUFFER = 0,
	SHADER_RESOURCE_TYPE_STRUCTURED_BUFFER,
	SHADER_RESOURCE_TYPE_TEXTURE,
	SHADER_RESORUCE_TYPE_RENDER_TARGET,
	SHADER_RESOURCE_TYPE_DEPTH_STENCIL,

	SHADER_RESOURCE_TYPE_COUNT
};

enum COMPONENT_TYPE : UINT8 {
	COMPONENT_TYPE_TRANSFORM = 0,
	COMPONENT_TYPE_MOVEMENT,			// undefined
	COMPONENT_TYPE_MESH,				// undefined
	COMPONENT_TYPE_MATERIAL,			// undefined
	COMPONENT_TYPE_ANIMATION,			// undefined
	COMPONENT_TYPE_BEHAVIOR_TREE,		// undefined

	COMPONENT_TYPE_COUNT
};

// =================
// Default Constants
// =================
constexpr D3D12_ROOT_SIGNATURE_FLAGS ROOT_SIGNATURE_FLAG_DEFAULT = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT |
D3D12_ROOT_SIGNATURE_FLAG_DENY_HULL_SHADER_ROOT_ACCESS |
D3D12_ROOT_SIGNATURE_FLAG_DENY_DOMAIN_SHADER_ROOT_ACCESS |
D3D12_ROOT_SIGNATURE_FLAG_DENY_GEOMETRY_SHADER_ROOT_ACCESS |
D3D12_ROOT_SIGNATURE_FLAG_DENY_PIXEL_SHADER_ROOT_ACCESS;
